SHELL=/bin/bash
CFLAGS=-Wall -Wextra
OUT=./a.out
CFILE=main.c
PASS=cqjxjnds

all: build run

build:
	$(CC) $(CFLAGS) -o $(OUT) $(CFILE)

run:
	# TODO write this in makefile
	chmod +x ./run.sh
	./run.sh
